Switch Ubuntu base image to 22.04 from 20.04
stellar/sep24-reference-ui pull request #7
Opened 2023-11-03 07:35 UTC by satyamz

2023-11-21 09:33 UTC, jacekn requested changes
Build is broken, needs investigation

2023-11-22 14:05 UTC, quietbits approved these changes

2023-11-22 15:04 UTC, jacekn approved these changes

2023-11-22 15:06 UTC, satyamz commented
@quietbits Can you please merge this PR?

2023-11-22 15:08 UTC, merged